# @author  Hoang Khac Phuc
# @email   hoangkhacphuc.dev@gmail.com
# @github  https://github.com/hoangkhacphuc

version: 2
updates:
  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "NightOwl-VN"
    assignees:
      - "NightOwl-VN"
    ignore:
      - dependency-name: "php"
        versions: [">= 8.4.0"]
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"
